[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  
[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Simple redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200