[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions"

# Redirect rules for Next.js app router and internationalization
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  headers = { Cache-Control = "public, max-age=31536000, immutable" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for PDPL compliance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' *.benefit.bh; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: blob: s3.me-south-1.amazonaws.com; connect-src 'self' *.benefit.bh *.tendzd.bh"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"